// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: communication.protos

package protos

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId int32 `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
}

func (x *RequestTask) Reset() {
	*x = RequestTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_protos_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTask) ProtoMessage() {}

func (x *RequestTask) ProtoReflect() protoreflect.Message {
	mi := &file_communication_protos_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTask.ProtoReflect.Descriptor instead.
func (*RequestTask) Descriptor() ([]byte, []int) {
	return file_communication_protos_rawDescGZIP(), []int{0}
}

func (x *RequestTask) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type GiveTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeTask string `protobuf:"bytes,1,opt,name=type_task,json=typeTask,proto3" json:"type_task,omitempty"`
}

func (x *GiveTask) Reset() {
	*x = GiveTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communication_protos_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveTask) ProtoMessage() {}

func (x *GiveTask) ProtoReflect() protoreflect.Message {
	mi := &file_communication_protos_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveTask.ProtoReflect.Descriptor instead.
func (*GiveTask) Descriptor() ([]byte, []int) {
	return file_communication_protos_rawDescGZIP(), []int{1}
}

func (x *GiveTask) GetTypeTask() string {
	if x != nil {
		return x.TypeTask
	}
	return ""
}

var File_communication_protos protoreflect.FileDescriptor

var file_communication_protos_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x2a, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x27, 0x0a, 0x08, 0x47, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x32, 0x36, 0x0a, 0x0b, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x0a, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x09, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x22, 0x00, 0x42, 0x65, 0x5a, 0x63, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6d, 0x75, 0x30, 0x31, 0x2f,
	0x54, 0x50, 0x31, 0x2d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73,
	0x2d, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x2f,
	0x62, 0x61, 0x73, 0x65, 0x2f, 0x6d, 0x61, 0x70, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_communication_protos_rawDescOnce sync.Once
	file_communication_protos_rawDescData = file_communication_protos_rawDesc
)

func file_communication_protos_rawDescGZIP() []byte {
	file_communication_protos_rawDescOnce.Do(func() {
		file_communication_protos_rawDescData = protoimpl.X.CompressGZIP(file_communication_protos_rawDescData)
	})
	return file_communication_protos_rawDescData
}

var file_communication_protos_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_communication_protos_goTypes = []interface{}{
	(*RequestTask)(nil), // 0: RequestTask
	(*GiveTask)(nil),    // 1: GiveTask
}
var file_communication_protos_depIdxs = []int32{
	0, // 0: Coordinator.AssignTask:input_type -> RequestTask
	1, // 1: Coordinator.AssignTask:output_type -> GiveTask
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_communication_protos_init() }
func file_communication_protos_init() {
	if File_communication_protos != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communication_protos_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communication_protos_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communication_protos_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_protos_goTypes,
		DependencyIndexes: file_communication_protos_depIdxs,
		MessageInfos:      file_communication_protos_msgTypes,
	}.Build()
	File_communication_protos = out.File
	file_communication_protos_rawDesc = nil
	file_communication_protos_goTypes = nil
	file_communication_protos_depIdxs = nil
}
